<?php

########################################################################
# Extension Manager/Repository config file for ext: "t3o_slack"
#
# Auto generated by Extension Builder 2015-11-07
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 't3o_slack',
	'description' => 'Sign Up for a slack installation',
	'category' => 'plugin',
	'author' => 'Stefan Busemann',
	'author_email' => 'stefan.busemann@typo3.org',
	'author_company' => 'TYPO3 Association',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.9.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
